### PR TITLE
Use goyek instead of Make

### PR DESCRIPTION
**Pull request by pellared**
## Why

Experiment with https://github.com/goyek/goyek/issues/59

## What 

- Switch to `goyek` from Make
- Move all tools dependencies to `build` Go module - including `goyek`
  - I do not want users of `fluentassert` to need to download `goyek`
  - Probably `goyek` should recommend doing it as well it also makes `go.mod` nicer as it separates build pipeline dependencies from actual "real" dependencies
- Add convenience scripts for Bash and PowerShell that can be executed from any location

### CODE REVIEW

**Review by dertseha — COMMENTED** [review]
Why do the build scripts change directory into `/build`, only to have the build script change back to root of the project?
If neither steps would be done, fewer logic would be necessary, and the `goyek` scripts would both be reduced to execute `go run build`.

**Comment by pellared** [comment]
> Why do the build scripts change directory into `/build`, only to have the build script change back to root of the project?
> If neither steps would be done, fewer logic would be necessary, and the `goyek` scripts would both be reduced to execute `go run build`.

Because `build` is a Go module so that I do not clutter the main (library's) `go.mod`.

See: 

```sh
$ go run ./build/
main module (github.com/pellared/fluentassert) does not contain package github.com/pellared/fluentassert/build
```

To execute `go run` you need to "be" inside the Go module path.

This is why `os.Chdir("..")` has been added.

I have an idea of how to create a workaround for this and would not require changes in Go code. Stay tuned 😉

**Comment by pellared** [comment]
@dertseha Here are the changes to make it IMO better: https://github.com/pellared/fluentassert/pull/2/commits/1c06297e3ea30bd629556bbeed911afe607e90df

Advantages:
- No need to run `os.Chdir("..")` in `build.go`
- AFAIK should work faster as `go build` uses Go build cache and `go run` does not

Disadvantage: 
- Requires changes in `.gitignore`

**Comment by dertseha** [comment]
I see the approach and I understand the reason behind it. I consider both approaches as compromises. Comparing the two solutions, I prefer the original one. *)
For me the appeal of `goyek` is to write one simple line on the CLI, and the rest is Go code. For this solution I need several steps + scripts again, which even includes a separate executable.

*) The third, and for me best, option would be to have `goyek` be in the root `go.mod` file. I don't have the feature-request of Go itself at hand, there is work/proposal ongoing that indirect dependencies not necessary for an app shall be skipped by `go mod` - so, if that went through, `goyek` would not end up in the `go.mod` files of users of the `fluentassert` library. I assume this issue being the reason that the `build` dir is a separate module.

**Comment by pellared** [comment]
I guess this the proposal: <https://github.com/golang/go/issues/36460> you are referring to. It still won't help with multi-module repositories. But I understand it would help getting rid of things like `tool/go.mod`. Also, it will work only for newer not yet released versions of Go. Therefore I still am not sure if the third option would be really the best one.

**Comment by pellared** [comment]
Another reason to use the first approach it makes debugging easier.

**Comment by pellared** [comment]
To make the first approach more user-friendly we can propose a breaking change here: https://github.com/goyek/goyek/issues/62 to add `os.Chdir("..")` to `Flow.Main()`.

**Comment by pellared** [comment]
@dertseha Merging this one. I will make a PR in https://github.com/goyek/goyek when I find more time.

**Comment by dertseha** [comment]
OK, the current approach seems to be a good compromise. It's the least amount of code and still allows to have the user stay in control.

**Pull request merged**
